### ISSUE TITLE
Presentation outline/ideas

### ISSUE THREAD

**Issue by spcanelon** [spcanelon/csvConf2021#2]
Hi @LizHareDogs. We have 15 minutes to give the talk and 5 minutes for Q&A. Broad guidelines I'm familiar with recommend spending at least 1 minute per slide, so we could be working with about 15 slides.

I'm creating a rough outline here to get us started on the discussion.

1. Title slide
2. Hello slide: who are we?
3. What's this talk about? What motivated the topic?
3. "Learning objectives:" what can people expect to walk away with?
5. What is TidyTuesday and how does it work? Connecting it to R for folks that are unfamiliar.
6. How is TidyTuesday data collected? How was alt text scraped from the images?
7. What results did we find? This will be a few slides probably.
8. How exactly do you write good alt text for a data visualization? At least a couple of slides (e.g. the rubric (see #1))
9. What are other places in R where we see a lack of alt text? E.g. online R books.
10. How has the tide started shifting? E.g. where are conversations about this happening (e.g. useR!2021)? What changes have we seen generally (e.g. new alt text code chunk option for R Markdown)? What changes have we noticed since announcing our talk?
8. What's the call to action? And where can people learn more (e.g. a short curated list resources)?
9. Goodbye slide: Thanks for having us and here's our contact information (websites, Twitter handles, GitHub)

**Comment by LizHareDogs** [comment]
This is great!

I'm really glad you took a stab at it first, because you have the educational perspective. If I'd done it, it would have been more research-focused just because that's what my background is.

> recommend spending at least 1 minute per slide, so we could be working with about 15 slides.
> 
Agree!

> I'm creating a rough outline here to get us started on the discussion.
> 
> 	• Title slide
> 	• Hello slide: who are we?
> 	• What's this talk about? What motivated the topic?
		What a screen reader is, and what it does and doesn't do (e.g. it reads static text on the screen, not graphics or text in videos (like Zoom screen-sharing).
		While some OSs and platforms (FaceBook, LinkedIn) have AI image recognition, it is not capable of describing data visualizations.
	Why do blind people need data visualizatioN? Current examples like Covid incidence maps (public health), election maps, and because blind researchers are out here crunching data, reading the literature, and sharing findings.
	R does not have the capability of producing readable charts, like SAS and Andy Stefik's program.

> 	• "Learning objectives:" what can people expect to walk away with?
		What are the essential features of alt-texts
		Why they shouldn't just repeat what's in the title or caption (in some documents, those thext elements will already be accessible, and they are not adequate to understand what the results.
> 	• What is TidyTuesday and how does it work? Connecting it to R for folks that are unfamiliar.
Development of learning communities like R4DS (https://www.rfordatasci.com -- ugh! a bunch of the first links on this page are unlabeled 🪠🪠🪠)
> 	• How is TidyTuesday data collected? How was alt text scraped from the images?
> 	• What results did we find? This will be a few slides probably.
		Agree that it's likely to be more than one.
		Overall and annual numbers of TidyTuesday Tweets
		Overall and annual percentages of TidyTuesday Tweets containing alt-text at all
		From my point of view: how many of these alt-texts don't actually tell me what the data are showing
		analysis according to rubric?
> 	• How exactly do you write good alt text for a data visualization? At least a couple of slides (e.g. the rubric (see #1))
		The rubric! And also: Do you have enough information to understand the purpose of the image without seeing it?
> 	• What are other places in R where we see a lack of alt text? E.g. online R books.
		Online R books, published R books that are made available digitally to people with print disabilities,  R documentation (e.g. gtsummary::tbl_summary has example output with no description), blogs (including ones from a certain for-profit R development company  that has little regard for accessibility)

> 	• How has the tide started shifting? E.g. where are conversations about this happening (e.g. useR!2021)? What changes have we seen generally (e.g. new alt text code chunk option for R Markdown)? What changes have we noticed
		Changes are just starting and slow.
		The alt-text thing for R Markdown is great, *but*  people will probably have to interrupt their workflow to describe what the data show after creating the graphic! If you want reproducible reports, you will still have to go back in and explain what the data show. This is why people are going to be tempted to put just the title-caption there and leave out the most crucial information. 
> since announcing our talk?
		This will be fun to find out!
> 	• What's the call to action? And where can people learn more (e.g. a short curated list resources)?
		WGBH Guide Guidelines for describing STEM images
https://www.wgbh.org/foundation/ncam/guidelines/guidelines-for-describing-stem-images
		Diagram Center Accessible Images
http://diagramcenter.org/making-images-accessible.html
		Diagram Center Accessible Math Tricks and Tips
http://diagramcenter.org/accessible-math-tools-tips-and-training.html
		Writing alt-text for data visualization
https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81
> 	• Goodbye slide: Thanks for having us and here's our contact information (websites, Twitter handles, GitHub)



Thanks for the great start, Silvia!

Liz
